name: Auto Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 获取latest release tag，cut切割无关内容。和仓库中LocalReleaseTag对比，之后输出tag给之后的步骤
      - name: Set Version
        id: set-version
        run: |
          TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/tags | grep 'name' | cut -d\" -f4 | head -1 | cut -c 9- )

          OnlineReleaseTag=${TAG}
          LocalReleaseTag=$(cat ReleaseTag | head -n1)

          echo "LocalReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "OnlineReleaseTag=${TAG}"

          if [ "${LocalReleaseTag}" != "${OnlineReleaseTag}" ]
          then
             echo "::set-output name=version::${TAG}"
             echo "::set-output name=status::success"
          fi

      # Build and push
      - name: Build and push
        if: steps.set-version.outputs.status == 'success'
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            superng6/qbittorrentee:${{ steps.set-version.outputs.version }}
            superng6/qbittorrentee:latest
