name: Auto Upload files to release

on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 获得仓库中的ReleaseTag
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)"

      # 缓存release tag，用作与下一次执行任务时获取到到release tag做对比
      - name: Cache tag
        id: cache-tag
        uses: actions/cache@v2
        with:
          path: ./tag/
          key: ${{ runner.os }}-tag-${{ steps.set-version.outputs.version }}

      # 获取将latest release tag，未命中缓存则更新ReleaseTag
      - name: Get latest release tag
        id: get-release-tag
        if: steps.cache-tag.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./tag
          echo ${{ steps.set-version.outputs.version }} > ./tag/tag-${{ steps.set-version.outputs.version }}
          echo "::set-output name=status::success"

      - name: Dowload release
        if: steps.get-release-tag.outputs.status == 'success'
        run: |
          mkdir ./qbittorrent
          cd ./qbittorrent
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_aarch64-linux-musl_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_arm-linux-musleabi_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_linux_x64_static.zip


      - name: Upload files to release
        if: steps.get-release-tag.outputs.status == 'success'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: qBittorrent Enhanced Edition v${{ steps.set-version.outputs.version }}
          tag_name: ${{ steps.set-version.outputs.version }}
          # body_path: Changelog
          files: |
            ./qbittorrent/*.zip
