name: Update ReleaseTag

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      # 获取latest release tag，cut切割无关内容。和仓库中LocalReleaseTag对比，之后输出tag给之后的步骤
      - name: Set Version
        id: set-version
        run: |
          TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/tags | grep 'name' | cut -d\" -f4 | head -1 | cut -c 9- )

          OnlineReleaseTag=${TAG}
          LocalReleaseTag=$(cat ReleaseTag | head -n1)

          echo "LocalReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "OnlineReleaseTag=${TAG}"

          if [ "${LocalReleaseTag}" != "${OnlineReleaseTag}" ]
          then
             echo "::set-output name=version::${TAG}"
             echo "::set-output name=status::success"
          fi

      # 将latest release tag写入到./ReleaseTag
      - name: Update ReleaseTag
        if: steps.set-version.outputs.status == 'success'
        run: |
          echo ${{ steps.set-version.outputs.version }} > ./ReleaseTag

      # push到GitHub的项目当中
      - name: Push
        if: steps.set-version.outputs.status == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update ReleaseTag ${{ steps.set-version.outputs.version }}"
          git push -v --progress
